version : '1.1'
services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME : development
      MONGO_INITDB_ROOT_PASSWORD : root123

  mongo-express:
    ports:
      - 8081:8081
      environment:
        ME_CONFIG_MONGO_INITDB_ROOT_USERNAME : development
        ME_CONFIG_MONGO_INITDB_ROOT_PASSWORD : root123
        ME_CONFIG_MONGODB_URL : mongodb://development:root123@mongo:27017
